### ISSUE TITLE
Requesting access to NTHU-DDD dataset

### ISSUE THREAD

**Issue by Hackerman28** [Aysenuryilmazz/Driver_Drowsiness_Detection#2]
I have been pursuing my final year of Bachelors of Engineering. For my final year project, I have been following works of drowsiness detection in Github and I came across your repo. I had then applied for the NTHU-DDD dataset myself with the necessary forms filled. But since many countries are struggling with coronavirus, my form has been ignored for more than 4 months. So can you share with me the data and if not the credentials provided to you to access the data. It would be helpful for me to complete my final year project.

**Comment by yi45skench** [comment]
你好，请问你找到该数据集了吗？可以分享一下吗，我也在研究该方向

**Comment by YuanFan9** [comment]
您好，请问能分享一下该数据集吗，我也在研究该方向

**Comment by yi45skench** [comment]
我也没得，正在努力搜索








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aysenuryilmazz/Driver_Drowsiness_Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Aysenuryilmazz/Driver_Drowsiness_Detection] Requesting access to NTHU-DDD dataset (#2)





 
您好，请问能分享一下该数据集吗，我也在研究该方向

**Comment by Aysenuryilmazz** [comment]
My advisor had shared the dataset with her own credential thats why now I can not share with you
